version: "3.8"

services:
  web:
    image: nginx:1.23-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    build:
      args:
        user: developer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "payment-api"
    ports:
      - "5432:5432"
